/**
 * Regenerates the pre-rendered HTML block in index.html from src/data.js.
 *
 * Why this exists: the site renders entirely from JavaScript, and the crawlers
 * that matter most for a portfolio -- LinkedIn, X, Slack, Discord, and the AI
 * crawlers -- do not run JavaScript. Without a static snapshot they fetch a
 * document with no words in it.
 *
 * The snapshot is progressive enhancement, not a second source of truth: the
 * live site always renders from data.js, so a stale snapshot degrades SEO but
 * never shows a visitor the wrong thing.
 *
 * Usage:  node build.js
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(fileURLToPath(import.meta.url));
const START = "<!-- prerender:start -->";
const END = "<!-- prerender:end -->";

const esc = (s) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);

const { portfolioData: d } = await import("./src/data.js");

const section = (id, heading, body) => `
        <section class="panel" id="prerender-${esc(id)}">
          <h2>${esc(heading)}</h2>
${body}
        </section>`;

const parts = [];

parts.push(
  section(
    "about",
    "About",
    d.about.bio.map((p) => `          <p>${esc(p)}</p>`).join("\n")
  )
);

parts.push(
  section(
    "education",
    "Education",
    d.education
      .map(
        (e) =>
          `          <p><strong>${esc(e.degree)}</strong>, ${esc(e.school)} (${esc(e.year)}). ${esc(e.description)}</p>`
      )
      .join("\n")
  )
);

parts.push(
  section(
    "experience",
    "Experience",
    d.experience
      .map(
        (x) =>
          `          <p><strong>${esc(x.title)}</strong>, ${esc(x.company)} (${esc(x.period)}).</p>\n` +
          `          <ul>${(x.highlights ?? []).map((h) => `<li>${esc(h)}</li>`).join("")}</ul>`
      )
      .join("\n")
  )
);

parts.push(
  section(
    "projects",
    "Projects",
    d.projects
      .map((p) => {
        const link = p.links?.github || p.links?.live;
        const name = link
          ? `<a href="${esc(link)}">${esc(p.name)}</a>`
          : esc(p.name);
        return `          <p><strong>${name}</strong> — ${esc(p.tagline)}. ${esc(p.description)} Tags: ${esc((p.tags ?? []).join(", "))}.</p>`;
      })
      .join("\n")
  )
);

parts.push(
  section(
    "skills",
    "Skills",
    d.skills
      .map((s) => `          <p><strong>${esc(s.category)}:</strong> ${esc((s.items ?? []).join(", "))}</p>`)
      .join("\n")
  )
);

parts.push(
  section(
    "publications",
    "Publications",
    d.publications
      .map((p) => {
        const title = p.links?.doi ? `<a href="${esc(p.links.doi)}">${esc(p.title)}</a>` : esc(p.title);
        return (
          `          <p><strong>${title}</strong>. ${esc((p.authors ?? []).join(", "))}. ${esc(p.venue)}.</p>` +
          (p.abstract ? `\n          <p>${esc(p.abstract)}</p>` : "")
        );
      })
      .join("\n")
  )
);

if (d.contact?.display !== false) {
  parts.push(
    section(
      "contact",
      "Contact",
      `          <p>${esc(d.contact.intro)}</p>\n` +
        `          <p>Email: <a href="mailto:${esc(d.contact.email)}">${esc(d.contact.email)}</a></p>`
    )
  );
}

const block = [
  START,
  "          <!-- Generated by `node build.js` from src/data.js. Gives crawlers and",
  "               link-preview bots real text, since they do not run JavaScript.",
  "               Replaced by the live render as soon as the module loads. -->",
  parts.join("\n").replace(/^\n/, ""),
  "          " + END,
].join("\n");

const file = join(root, "index.html");
const src = await readFile(file, "utf8");
const from = src.indexOf(START);
const to = src.indexOf(END);
if (from === -1 || to === -1) {
  throw new Error(`index.html is missing the ${START} / ${END} markers`);
}

let out = src.slice(0, from) + block.trimStart() + src.slice(to + END.length);

/* ── Keep the head in sync with data.js ──
   The description appears in four places and the research list in one more.
   Rewriting them from the same source is the only way they stay consistent
   as the research focus changes. */
const tagline = d.profile.tagline ?? "";
const withName = `${d.profile.name} — ${tagline}`;

const setMeta = (attr, name, value) => {
  const re = new RegExp(`(<meta\\s+${attr}="${name}"[^>]*?content=")[^"]*(")`, "i");
  if (!re.test(out)) {
    console.warn(`  ! no ${attr}="${name}" tag to update`);
    return;
  }
  out = out.replace(re, `$1${escAttr(value)}$2`);
};

setMeta("name", "description", withName);
setMeta("property", "og:description", tagline);
setMeta("name", "twitter:description", tagline);

// Multi-line <meta> tags (prettier wraps long ones) need a looser pattern.
out = out.replace(
  /(<meta\s+name="description"[\s\S]*?content=")[\s\S]*?(")/i,
  `$1${escAttr(withName)}$2`
);

// JSON-LD description + knowsAbout
out = out.replace(
  /("description":\s*")[^"]*(")/,
  `$1${escAttr(withName)}$2`
);
if (Array.isArray(d.profile.researchAreas)) {
  out = out.replace(
    /("knowsAbout":\s*)\[[^\]]*\]/,
    `$1${JSON.stringify(d.profile.researchAreas)}`
  );
}

await writeFile(file, out, "utf8");

function escAttr(s) {
  return String(s).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}

const words = block.replace(/<[^>]+>/g, " ").split(/\s+/).filter(Boolean).length;
console.log(
  `index.html updated — ${parts.length} sections, ~${words} indexable words, head description + knowsAbout synced`
);
