/**
 * Regenerates the pre-rendered HTML block in index.html from src/data.js.
 *
 * Why this exists: the site renders entirely from JavaScript, and the crawlers
 * that matter most for a portfolio -- LinkedIn, X, Slack, Discord, and the AI
 * crawlers -- do not run JavaScript. Without a static snapshot they fetch a
 * document with no words in it.
 *
 * The snapshot is progressive enhancement, not a second source of truth: the
 * live site always renders from data.js, so a stale snapshot degrades SEO but
 * never shows a visitor the wrong thing.
 *
 * Usage:  node build.js
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(fileURLToPath(import.meta.url));
const START = "<!-- prerender:start -->";
const END = "<!-- prerender:end -->";

const esc = (s) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);

const { portfolioData: d } = await import("./src/data.js");

const section = (id, heading, body) => `
        <section class="panel" id="prerender-${esc(id)}">
          <h2>${esc(heading)}</h2>
${body}
        </section>`;

const parts = [];

parts.push(
  section(
    "about",
    "About",
    d.about.bio.map((p) => `          <p>${esc(p)}</p>`).join("\n")
  )
);

parts.push(
  section(
    "education",
    "Education",
    d.education
      .map(
        (e) =>
          `          <p><strong>${esc(e.degree)}</strong>, ${esc(e.school)} (${esc(e.year)}). ${esc(e.description)}</p>`
      )
      .join("\n")
  )
);

parts.push(
  section(
    "experience",
    "Experience",
    d.experience
      .map(
        (x) =>
          `          <p><strong>${esc(x.title)}</strong>, ${esc(x.company)} (${esc(x.period)}).</p>\n` +
          `          <ul>${(x.highlights ?? []).map((h) => `<li>${esc(h)}</li>`).join("")}</ul>`
      )
      .join("\n")
  )
);

parts.push(
  section(
    "projects",
    "Projects",
    d.projects
      .map((p) => {
        const link = p.links?.github || p.links?.live;
        const name = link
          ? `<a href="${esc(link)}">${esc(p.name)}</a>`
          : esc(p.name);
        return `          <p><strong>${name}</strong> — ${esc(p.tagline)}. ${esc(p.description)} Tags: ${esc((p.tags ?? []).join(", "))}.</p>`;
      })
      .join("\n")
  )
);

parts.push(
  section(
    "skills",
    "Skills",
    d.skills
      .map((s) => `          <p><strong>${esc(s.category)}:</strong> ${esc((s.items ?? []).join(", "))}</p>`)
      .join("\n")
  )
);

parts.push(
  section(
    "publications",
    "Publications",
    d.publications
      .map((p) => {
        const title = p.links?.doi ? `<a href="${esc(p.links.doi)}">${esc(p.title)}</a>` : esc(p.title);
        return (
          `          <p><strong>${title}</strong>. ${esc((p.authors ?? []).join(", "))}. ${esc(p.venue)}.</p>` +
          (p.abstract ? `\n          <p>${esc(p.abstract)}</p>` : "")
        );
      })
      .join("\n")
  )
);

if (d.contact?.display !== false) {
  parts.push(
    section(
      "contact",
      "Contact",
      `          <p>${esc(d.contact.intro)}</p>\n` +
        `          <p>Email: <a href="mailto:${esc(d.contact.email)}">${esc(d.contact.email)}</a></p>`
    )
  );
}

const block = [
  START,
  "          <!-- Generated by `node build.js` from src/data.js. Gives crawlers and",
  "               link-preview bots real text, since they do not run JavaScript.",
  "               Replaced by the live render as soon as the module loads. -->",
  parts.join("\n").replace(/^\n/, ""),
  "          " + END,
].join("\n");

const file = join(root, "index.html");
const src = await readFile(file, "utf8");
const from = src.indexOf(START);
const to = src.indexOf(END);
if (from === -1 || to === -1) {
  throw new Error(`index.html is missing the ${START} / ${END} markers`);
}

const out = src.slice(0, from) + block.trimStart() + src.slice(to + END.length);
await writeFile(file, out, "utf8");

const words = block.replace(/<[^>]+>/g, " ").split(/\s+/).filter(Boolean).length;
console.log(`index.html prerender block updated — ${parts.length} sections, ~${words} indexable words`);
